version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: designsight-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: designsight
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - designsight-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: designsight-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/designsight?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      CLIENT_URL: http://localhost:3000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MAX_FILE_SIZE: 10485760
      UPLOAD_PATH: /app/uploads
      AI_MODEL: gpt-4-vision-preview
      MAX_ANALYSIS_RETRIES: 3
      ANALYSIS_TIMEOUT: 30000
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - designsight-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: designsight-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - server
    networks:
      - designsight-network

volumes:
  mongodb_data:

networks:
  designsight-network:
    driver: bridge


